using MonoMod.RuntimeDetour;
using MonoMod.RuntimeDetour.HookGen;
namespace HKMirror.Hooks.OnHooks;
/// <summary>
/// Contains different types of On Hooks for LiftPlatform class.<br />
/// Contains hooks that aren't generated by monomod, and before and after orig hooks for easier hooking.
/// </summary>
public static class OnLiftPlatform
{
internal static class HookHandler
{
private static List<string> HookedList = new List<string>();
internal static void HookStart()
{
if (!HookedList.Contains("Start"))
{
HookedList.Add("Start");
On.LiftPlatform.Start += Start;

}
}
internal static event Delegates.Start_BeforeArgs _beforeStart;
internal static event Delegates.Start_AfterArgs _afterStart;
private static void Start(On.LiftPlatform.orig_Start orig,LiftPlatform self)
{
Delegates.Params_Start @params = new() 
{
self = self
};
if (_beforeStart != null)
{
foreach (Delegates.Start_BeforeArgs toInvoke in _beforeStart.GetInvocationList())
{
try
{
_beforeStart?.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
self = @params.self;
orig(self);
if (_afterStart != null)
{
foreach (Delegates.Start_AfterArgs toInvoke in _afterStart.GetInvocationList())
{
try
{
_afterStart.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
}
internal static void HookUpdate()
{
if (!HookedList.Contains("Update"))
{
HookedList.Add("Update");
On.LiftPlatform.Update += Update;

}
}
internal static event Delegates.Update_BeforeArgs _beforeUpdate;
internal static event Delegates.Update_AfterArgs _afterUpdate;
private static void Update(On.LiftPlatform.orig_Update orig,LiftPlatform self)
{
Delegates.Params_Update @params = new() 
{
self = self
};
if (_beforeUpdate != null)
{
foreach (Delegates.Update_BeforeArgs toInvoke in _beforeUpdate.GetInvocationList())
{
try
{
_beforeUpdate?.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
self = @params.self;
orig(self);
if (_afterUpdate != null)
{
foreach (Delegates.Update_AfterArgs toInvoke in _afterUpdate.GetInvocationList())
{
try
{
_afterUpdate.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
}
internal static void HookOnCollisionEnter2D()
{
if (!HookedList.Contains("OnCollisionEnter2D"))
{
HookedList.Add("OnCollisionEnter2D");
On.LiftPlatform.OnCollisionEnter2D += OnCollisionEnter2D;

}
}
internal static event Delegates.OnCollisionEnter2D_BeforeArgs _beforeOnCollisionEnter2D;
internal static event Delegates.OnCollisionEnter2D_AfterArgs _afterOnCollisionEnter2D;
private static void OnCollisionEnter2D(On.LiftPlatform.orig_OnCollisionEnter2D orig,LiftPlatform self,  UnityEngine.Collision2D collision)
{
Delegates.Params_OnCollisionEnter2D @params = new() 
{
self = self
, collision = collision
};
if (_beforeOnCollisionEnter2D != null)
{
foreach (Delegates.OnCollisionEnter2D_BeforeArgs toInvoke in _beforeOnCollisionEnter2D.GetInvocationList())
{
try
{
_beforeOnCollisionEnter2D?.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
self = @params.self;
collision = @params.collision;
orig(self, collision);
if (_afterOnCollisionEnter2D != null)
{
foreach (Delegates.OnCollisionEnter2D_AfterArgs toInvoke in _afterOnCollisionEnter2D.GetInvocationList())
{
try
{
_afterOnCollisionEnter2D.Invoke(@params);
}
catch (Exception e) 
{ HKMirrorMod.DoLogError(e);
}
}
}
}
}

/// <summary>
/// Contains necessary information to create Hooks. Does not contain any hooks
/// </summary>
public static class Delegates
{
public sealed class Params_Start
{
public LiftPlatform self;
}
public delegate void Start_BeforeArgs(Params_Start args);
public delegate void Start_AfterArgs(Params_Start args);
public delegate void Start_WithArgs (Action<LiftPlatform> orig, LiftPlatform self);
public sealed class Params_Update
{
public LiftPlatform self;
}
public delegate void Update_BeforeArgs(Params_Update args);
public delegate void Update_AfterArgs(Params_Update args);
public delegate void Update_WithArgs (Action<LiftPlatform> orig, LiftPlatform self);
public sealed class Params_OnCollisionEnter2D
{
public LiftPlatform self;
public UnityEngine.Collision2D collision;
}
public delegate void OnCollisionEnter2D_BeforeArgs(Params_OnCollisionEnter2D args);
public delegate void OnCollisionEnter2D_AfterArgs(Params_OnCollisionEnter2D args);
public delegate void OnCollisionEnter2D_WithArgs (Action<LiftPlatform,  UnityEngine.Collision2D> orig, LiftPlatform self,  UnityEngine.Collision2D collision);
}

/// <summary>
/// Contains Hooks to that run code before orig(self) is called
/// </summary>
public static class BeforeOrig
{
public static event Delegates.Start_BeforeArgs Start
{
add
{

HookHandler._beforeStart += value;
HookHandler.HookStart();
}
remove => HookHandler._beforeStart -= value;
}
public static event Delegates.Update_BeforeArgs Update
{
add
{

HookHandler._beforeUpdate += value;
HookHandler.HookUpdate();
}
remove => HookHandler._beforeUpdate -= value;
}
public static event Delegates.OnCollisionEnter2D_BeforeArgs OnCollisionEnter2D
{
add
{

HookHandler._beforeOnCollisionEnter2D += value;
HookHandler.HookOnCollisionEnter2D();
}
remove => HookHandler._beforeOnCollisionEnter2D -= value;
}
}

/// <summary>
/// Contains Hooks to that run code after orig(self) is called
/// </summary>
public static class AfterOrig
{
public static event Delegates.Start_AfterArgs Start
{
add
{

HookHandler._afterStart += value;
HookHandler.HookStart();
}
remove => HookHandler._afterStart -= value;
}
public static event Delegates.Update_AfterArgs Update
{
add
{

HookHandler._afterUpdate += value;
HookHandler.HookUpdate();
}
remove => HookHandler._afterUpdate -= value;
}
public static event Delegates.OnCollisionEnter2D_AfterArgs OnCollisionEnter2D
{
add
{

HookHandler._afterOnCollisionEnter2D += value;
HookHandler.HookOnCollisionEnter2D();
}
remove => HookHandler._afterOnCollisionEnter2D -= value;
}
}

/// <summary>
/// Contains all On Hooks, even those that aren't in the On namespace such as API generated functions and property getters/setters
/// </summary>
public static class WithOrig
{
public static event On.LiftPlatform.hook_Start Start
{
add => On.LiftPlatform.Start += value;
remove => On.LiftPlatform.Start -= value;
}
public static event On.LiftPlatform.hook_Update Update
{
add => On.LiftPlatform.Update += value;
remove => On.LiftPlatform.Update -= value;
}
public static event On.LiftPlatform.hook_OnCollisionEnter2D OnCollisionEnter2D
{
add => On.LiftPlatform.OnCollisionEnter2D += value;
remove => On.LiftPlatform.OnCollisionEnter2D -= value;
}
}

}
