using MonoMod.RuntimeDetour;
using MonoMod.RuntimeDetour.HookGen;

namespace HKMirror.Hooks.OnHooks;

/// <summary>
/// Contains different types of On Hooks for RuinsLift class.<br />
/// Contains hooks that aren't generated by monomod, and before and after orig hooks for easier hooking.
/// </summary>
public static class OnRuinsLift
{
    internal static class HookHandler
    {
        private static List<string> HookedList = new List<string>();

        internal static void HookStart()
        {
            if (!HookedList.Contains("Start"))
            {
                HookedList.Add("Start");
                On.RuinsLift.Start += Start;
            }
        }

        internal static event Delegates.Start_BeforeArgs _beforeStart;
        internal static event Delegates.Start_AfterArgs _afterStart;

        private static void Start(On.RuinsLift.orig_Start orig, RuinsLift self)
        {
            Delegates.Params_Start @params = new()
            {
                self = self
            };
            if (_beforeStart != null)
            {
                foreach (Delegates.Start_BeforeArgs toInvoke in _beforeStart.GetInvocationList())
                {
                    try
                    {
                        _beforeStart?.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            self = @params.self;
            orig(self);
            if (_afterStart != null)
            {
                foreach (Delegates.Start_AfterArgs toInvoke in _afterStart.GetInvocationList())
                {
                    try
                    {
                        _afterStart.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }
        }

        internal static void HookHideChains()
        {
            if (!HookedList.Contains("HideChains"))
            {
                HookedList.Add("HideChains");
                On.RuinsLift.HideChains += HideChains;
            }
        }

        internal static event Delegates.HideChains_BeforeArgs _beforeHideChains;

        private static System.Collections.IEnumerator HideChains(On.RuinsLift.orig_HideChains orig, RuinsLift self)
        {
            Delegates.Params_HideChains @params = new()
            {
                self = self
            };
            if (_beforeHideChains != null)
            {
                foreach (Delegates.HideChains_BeforeArgs toInvoke in _beforeHideChains.GetInvocationList())
                {
                    try
                    {
                        _beforeHideChains?.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            self = @params.self;
            return orig(self);
        }

        internal static void HookGetPositionY()
        {
            if (!HookedList.Contains("GetPositionY"))
            {
                HookedList.Add("GetPositionY");
                On.RuinsLift.GetPositionY += GetPositionY;
            }
        }

        internal static event Delegates.GetPositionY_BeforeArgs _beforeGetPositionY;
        internal static event Delegates.GetPositionY_AfterArgs _afterGetPositionY;

        private static float GetPositionY(On.RuinsLift.orig_GetPositionY orig, RuinsLift self, int position)
        {
            Delegates.Params_GetPositionY @params = new()
            {
                self = self, position = position
            };
            if (_beforeGetPositionY != null)
            {
                foreach (Delegates.GetPositionY_BeforeArgs toInvoke in _beforeGetPositionY.GetInvocationList())
                {
                    try
                    {
                        _beforeGetPositionY?.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            self = @params.self;
            position = @params.position;
            var retVal = orig(self, position);
            if (_afterGetPositionY != null)
            {
                foreach (Delegates.GetPositionY_AfterArgs toInvoke in _afterGetPositionY.GetInvocationList())
                {
                    try
                    {
                        retVal = _afterGetPositionY.Invoke(@params, retVal);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            return retVal;
        }

        internal static void HookIsCurrentPositionTerminus()
        {
            if (!HookedList.Contains("IsCurrentPositionTerminus"))
            {
                HookedList.Add("IsCurrentPositionTerminus");
                On.RuinsLift.IsCurrentPositionTerminus += IsCurrentPositionTerminus;
            }
        }

        internal static event Delegates.IsCurrentPositionTerminus_BeforeArgs _beforeIsCurrentPositionTerminus;
        internal static event Delegates.IsCurrentPositionTerminus_AfterArgs _afterIsCurrentPositionTerminus;

        private static bool IsCurrentPositionTerminus(On.RuinsLift.orig_IsCurrentPositionTerminus orig, RuinsLift self,
            int position)
        {
            Delegates.Params_IsCurrentPositionTerminus @params = new()
            {
                self = self, position = position
            };
            if (_beforeIsCurrentPositionTerminus != null)
            {
                foreach (Delegates.IsCurrentPositionTerminus_BeforeArgs toInvoke in _beforeIsCurrentPositionTerminus
                             .GetInvocationList())
                {
                    try
                    {
                        _beforeIsCurrentPositionTerminus?.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            self = @params.self;
            position = @params.position;
            var retVal = orig(self, position);
            if (_afterIsCurrentPositionTerminus != null)
            {
                foreach (Delegates.IsCurrentPositionTerminus_AfterArgs toInvoke in _afterIsCurrentPositionTerminus
                             .GetInvocationList())
                {
                    try
                    {
                        retVal = _afterIsCurrentPositionTerminus.Invoke(@params, retVal);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            return retVal;
        }

        internal static void HookKeepInBounds()
        {
            if (!HookedList.Contains("KeepInBounds"))
            {
                HookedList.Add("KeepInBounds");
                On.RuinsLift.KeepInBounds += KeepInBounds;
            }
        }

        internal static event Delegates.KeepInBounds_BeforeArgs _beforeKeepInBounds;
        internal static event Delegates.KeepInBounds_AfterArgs _afterKeepInBounds;

        private static int KeepInBounds(On.RuinsLift.orig_KeepInBounds orig, RuinsLift self, int position)
        {
            Delegates.Params_KeepInBounds @params = new()
            {
                self = self, position = position
            };
            if (_beforeKeepInBounds != null)
            {
                foreach (Delegates.KeepInBounds_BeforeArgs toInvoke in _beforeKeepInBounds.GetInvocationList())
                {
                    try
                    {
                        _beforeKeepInBounds?.Invoke(@params);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            self = @params.self;
            position = @params.position;
            var retVal = orig(self, position);
            if (_afterKeepInBounds != null)
            {
                foreach (Delegates.KeepInBounds_AfterArgs toInvoke in _afterKeepInBounds.GetInvocationList())
                {
                    try
                    {
                        retVal = _afterKeepInBounds.Invoke(@params, retVal);
                    }
                    catch (Exception e)
                    {
                        HKMirrorMod.DoLogError(e);
                    }
                }
            }

            return retVal;
        }
    }

    /// <summary>
    /// Contains necessary information to create Hooks. Does not contain any hooks
    /// </summary>
    public static class Delegates
    {
        public sealed class Params_Start
        {
            public RuinsLift self;
        }

        public delegate void Start_BeforeArgs(Params_Start args);

        public delegate void Start_AfterArgs(Params_Start args);

        public delegate void Start_WithArgs(Action<RuinsLift> orig, RuinsLift self);

        public sealed class Params_HideChains
        {
            public RuinsLift self;
        }

        public delegate void HideChains_BeforeArgs(Params_HideChains args);

        public delegate System.Collections.IEnumerator HideChains_AfterArgs(Params_HideChains args,
            System.Collections.IEnumerator ret);

        public delegate System.Collections.IEnumerator HideChains_WithArgs(
            Func<RuinsLift, System.Collections.IEnumerator> orig, RuinsLift self);

        public sealed class Params_GetPositionY
        {
            public RuinsLift self;
            public int position;
        }

        public delegate void GetPositionY_BeforeArgs(Params_GetPositionY args);

        public delegate float GetPositionY_AfterArgs(Params_GetPositionY args, float ret);

        public delegate float GetPositionY_WithArgs(Func<RuinsLift, int, float> orig, RuinsLift self, int position);

        public sealed class Params_IsCurrentPositionTerminus
        {
            public RuinsLift self;
            public int position;
        }

        public delegate void IsCurrentPositionTerminus_BeforeArgs(Params_IsCurrentPositionTerminus args);

        public delegate bool IsCurrentPositionTerminus_AfterArgs(Params_IsCurrentPositionTerminus args, bool ret);

        public delegate bool IsCurrentPositionTerminus_WithArgs(Func<RuinsLift, int, bool> orig, RuinsLift self,
            int position);

        public sealed class Params_KeepInBounds
        {
            public RuinsLift self;
            public int position;
        }

        public delegate void KeepInBounds_BeforeArgs(Params_KeepInBounds args);

        public delegate int KeepInBounds_AfterArgs(Params_KeepInBounds args, int ret);

        public delegate int KeepInBounds_WithArgs(Func<RuinsLift, int, int> orig, RuinsLift self, int position);
    }

    /// <summary>
    /// Contains Hooks to that run code before orig(self) is called
    /// </summary>
    public static class BeforeOrig
    {
        public static event Delegates.Start_BeforeArgs Start
        {
            add
            {
                HookHandler._beforeStart += value;
                HookHandler.HookStart();
            }
            remove => HookHandler._beforeStart -= value;
        }

        public static event Delegates.HideChains_BeforeArgs HideChains
        {
            add
            {
                HookHandler._beforeHideChains += value;
                HookHandler.HookHideChains();
            }
            remove => HookHandler._beforeHideChains -= value;
        }

        public static event Delegates.GetPositionY_BeforeArgs GetPositionY
        {
            add
            {
                HookHandler._beforeGetPositionY += value;
                HookHandler.HookGetPositionY();
            }
            remove => HookHandler._beforeGetPositionY -= value;
        }

        public static event Delegates.IsCurrentPositionTerminus_BeforeArgs IsCurrentPositionTerminus
        {
            add
            {
                HookHandler._beforeIsCurrentPositionTerminus += value;
                HookHandler.HookIsCurrentPositionTerminus();
            }
            remove => HookHandler._beforeIsCurrentPositionTerminus -= value;
        }

        public static event Delegates.KeepInBounds_BeforeArgs KeepInBounds
        {
            add
            {
                HookHandler._beforeKeepInBounds += value;
                HookHandler.HookKeepInBounds();
            }
            remove => HookHandler._beforeKeepInBounds -= value;
        }
    }

    /// <summary>
    /// Contains Hooks to that run code after orig(self) is called
    /// </summary>
    public static class AfterOrig
    {
        public static event Delegates.Start_AfterArgs Start
        {
            add
            {
                HookHandler._afterStart += value;
                HookHandler.HookStart();
            }
            remove => HookHandler._afterStart -= value;
        }

        public static event Delegates.GetPositionY_AfterArgs GetPositionY
        {
            add
            {
                HookHandler._afterGetPositionY += value;
                HookHandler.HookGetPositionY();
            }
            remove => HookHandler._afterGetPositionY -= value;
        }

        public static event Delegates.IsCurrentPositionTerminus_AfterArgs IsCurrentPositionTerminus
        {
            add
            {
                HookHandler._afterIsCurrentPositionTerminus += value;
                HookHandler.HookIsCurrentPositionTerminus();
            }
            remove => HookHandler._afterIsCurrentPositionTerminus -= value;
        }

        public static event Delegates.KeepInBounds_AfterArgs KeepInBounds
        {
            add
            {
                HookHandler._afterKeepInBounds += value;
                HookHandler.HookKeepInBounds();
            }
            remove => HookHandler._afterKeepInBounds -= value;
        }
    }

    /// <summary>
    /// Contains all On Hooks, even those that aren't in the On namespace such as API generated functions and property getters/setters
    /// </summary>
    public static class WithOrig
    {
        public static event On.RuinsLift.hook_Start Start
        {
            add => On.RuinsLift.Start += value;
            remove => On.RuinsLift.Start -= value;
        }

        public static event On.RuinsLift.hook_HideChains HideChains
        {
            add => On.RuinsLift.HideChains += value;
            remove => On.RuinsLift.HideChains -= value;
        }

        public static event On.RuinsLift.hook_GetPositionY GetPositionY
        {
            add => On.RuinsLift.GetPositionY += value;
            remove => On.RuinsLift.GetPositionY -= value;
        }

        public static event On.RuinsLift.hook_IsCurrentPositionTerminus IsCurrentPositionTerminus
        {
            add => On.RuinsLift.IsCurrentPositionTerminus += value;
            remove => On.RuinsLift.IsCurrentPositionTerminus -= value;
        }

        public static event On.RuinsLift.hook_KeepInBounds KeepInBounds
        {
            add => On.RuinsLift.KeepInBounds += value;
            remove => On.RuinsLift.KeepInBounds -= value;
        }
    }
}